### ISSUE TITLE
Workflow is using the old version of `yamf` as it is not updated in `payu/dev`

### ISSUE THREAD

**Issue by CodeGat** [ACCESS-NRI/model-config-inputs#21]
See commit eaf85313c3b493f2de69d9889f2019ab33a9697d which is using the old version of `yamf` (note that the only manifest is the `README.md` rather than multiple entries. This is because the old functionality of `--force` was to overwrite the file each time it was called. 

We have updated the codebase in ACCESS-NRI/yamanifest#18, but haven't deployed the change onto `payu/dev` because we haven't packaged up `yamanifest`. 

## TODOs

 - [x] Package up and publish the updated `yamanifest`
 - [x] Trigger a build of `payu/dev`
 - [x] Update the `.manifest.yaml` file on Gadi and commit back the result to this remote

Tagging @jo-basevi

**Comment by CodeGat** [comment]
Closing this despite `yamanifest` CD not being implemented, since the source is complete.
